/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import java.util.Map;

public class JsonParser {
    private JsonTokenizer jsonTokenizer;
    private JsonObjectConverter jsonObjectConverter;

    public JsonParser(JsonTokenizer jsonTokenizer, JsonObjectConverter jsonObjectConverter) {
        this.jsonTokenizer = jsonTokenizer;
        this.jsonObjectConverter = jsonObjectConverter;
    }

    public Map<String, Object> parse(String json) {
        final List<Token> tokens = jsonTokenizer.tokenize(json);
        return jsonObjectConverter.parse(tokens);
    }
}

class JsonStack {

}
