/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class JsonParserTest {
    private JsonParser jsonParser;

    @BeforeEach
    public void setUp() {
        jsonParser = new JsonParser(new JsonTokenizer(), new JsonObjectConverter());
    }

    @Test
    public void emptyJson() {
        Assertions.assertEquals(new HashMap<>(), jsonParser.parse("{}"));
    }

    @Test
    public void simpleTextField() {
        Map<String, Object> parsedObject = jsonParser.parse("{\"name\" : \"lokesh\"}");

        Map<String, Object> expectedObject = new HashMap<>();
        expectedObject.put("name", "lokesh");
        Assertions.assertEquals(expectedObject, parsedObject);
    }

    @Test
    public void complexExample() {
        Map<String, Object> parsedObject = jsonParser.parse("{\"name\" : {\"first\" : \"lokesh\", \"last\" : \"pant\" }," +
                "\"address\" : { \"street\" : \"5th_Avenue\",  \"house_number\" : \"205\", \"pin\" : \"12345\", city\": \"Wonderland\" }");


        final Map<String, Object> expectedName = new HashMap<>();
        expectedName.put("first", "lokesh");
        expectedName.put("last", "pant");

        Map<String, Object> expectedAddress = new HashMap<>();

        expectedAddress.put("street", "5th_Avenue");
        expectedAddress.put("house_number", "205");
        expectedAddress.put("pin", "12345");
        expectedAddress.put("city", "Wonderland");


        Map<String, Object> expected = new HashMap<>();
        expected.put("name", expectedName);
        expected.put("address", expectedAddress);

        Assertions.assertEquals(expected, parsedObject);
    }
}
